/**
 * Concatenates src/*.css into dist/talwinder.css and writes a minified
 * twin. Deliberately dependency-free: the framework promises no build
 * step for users, and it would be odd for the framework itself to need
 * a toolchain to produce one file.
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { gzipSync } from "node:zlib";

const SRC = "src";
const VERSION = "1.0.0";

const banner = `/*!
 * TalwinderCSS v${VERSION}
 * Indian art traditions as a CSS framework.
 * https://arihant25.github.io/talwindercss
 * MIT licensed.
 *
 * Built from src/. Do not edit this file directly.
 */
`;

const files = readdirSync(SRC).filter((f) => f.endsWith(".css")).sort();
const css = banner + files.map((f) => readFileSync(join(SRC, f), "utf8")).join("\n");

writeFileSync("dist/talwinder.css", css);

/* Minifier. Comments are stripped except the leading banner. The
   negative lookahead on url( keeps data URIs intact, since the SVG
   masks contain both braces and semicolons. */
const min =
  banner +
  css
    .replace(/\/\*[^!][\s\S]*?\*\//g, "")
    .replace(/\/\*![\s\S]*?\*\//g, "")
    .replace(/\s+/g, " ")
    .replace(/\s*([{}:;,>])\s*/g, "$1")
    .replace(/;}/g, "}")
    .trim();

writeFileSync("dist/talwinder.min.css", min);

const kb = (s) => (Buffer.byteLength(s) / 1024).toFixed(1);
console.log(`talwinder.css      ${kb(css)} KB`);
console.log(`talwinder.min.css  ${kb(min)} KB`);
console.log(`gzipped            ${(gzipSync(min).length / 1024).toFixed(1)} KB`);
console.log(`sources            ${files.join(", ")}`);
